### PR TITLE
[IMP] Add @staticmethod to prevent Python Warning

### PR DESCRIPTION
**Pull request by 0ddlyoko**

### CODE REVIEW

**Comment by Geolykt** [comment]
Do you think this will work with all (if not most) Python interpreters?

**Comment by 0ddlyoko** [comment]
> Do you think this will work with all (if not most) Python interpreters?

This PR is to avoid having [this](https://prnt.sc/uk1icx) kind of situation, it should work with all Python interpreters

**Comment by ntoskrnl4** [comment]
> Do you think this will work with all (if not most) Python interpreters?

Static methods should be supported on any half-functional Python implementation, yes

**Review by Geolykt — APPROVED** [review]
Unrelated, but the key() function is pretty indescriptive in terms of name

**Comment by ntoskrnl4** [comment]
> Unrelated, but the key() function is pretty indescriptive in terms of name

It could also be made simply an attribute of the class instead of a function

**Comment by 0ddlyoko** [comment]
Yep but this should be done in another PR

**Comment by Geolykt** [comment]
So anyone against a merge of this PR?

**Review by ntoskrnl4 — APPROVED** [review]

**Pull request merged**
