### PR TITLE
Support for non-linux OS'es

### PR DESCRIPTION
**Pull request by kevdagoat**
I have implemented a small change to the initial handler to allow it to be run on multiple platforms. Confirmed working on Windows.

Note: This change will get all system CPU's, not the usable ones, as some platforms do not support the getaffinity syscall.

### CODE REVIEW

**Comment by Zulfen** [comment]
Does ```multiprocessing.cpu_count()``` only work correctly on Windows? If not, would just having that to check for available CPU's be simpler? Correct me if I am wrong of course.

**Comment by Geolykt** [comment]
From the Python Docs:
<pre>

multiprocessing.cpu_count()

    Return the number of CPUs in the system.

    This number is not equivalent to the number of CPUs the current process can use. The number of usable CPUs can be obtained with len(os.sched_getaffinity(0))

    May raise NotImplementedError.

    See also

    os.cpu_count()
</pre>
So dangerous when working with VMs (Virtual Private Servers)

**Comment by Zulfen** [comment]
Oh okay, thanks for letting me know - didn't know this!

**Comment by kevdagoat** [comment]
No, full Multiplatform support, any OS that supports more than one core :)

**Comment by ntoskrnl4** [comment]
> So dangerous when working with VMs (Virtual Private Servers)

Maybe, but not really.

The reason the `sched_getaffinity` call is preferred over `cpu_count` is that it is possible for the OS to set a process's CPU affinity such that it can only be scheduled onto certain cores. This means that the program is still running on an n-core system, but only a subset of those cores are able to be used by the program.

In most cloud servers/environments, virtualized servers are given only a few cores. Since they run full VMs, that VM OS only has those few cores, and not the 16/32/whatever of the actual host. Thus, the program will only see the number of cores the OS is running on, and not any outside information about the hypervisor or host. This is not a security vulnerability.

Now, whether we can use the cores given to the host is indeed a different problem, but setting a process's CPU affinity is not something significantly done (it will nearly always be the same number of cpus as the system OS). I'm down to make that call just a simple `multiprocessing.cpu_count()`, especially since it's supported by nearly all operating systems, but if we really want CPU affinity a good Windows workaround might be to call into `cffi` or the Win32 api.

**Pull request merged**
