### PR TITLE
Add Data File parser

### PR DESCRIPTION
**Pull request by 0ddlyoko**
This PR add a simple parser that will parse Data Files generated by Minecraft.
This parser can parse any json files like blocks, advancements, recipes or more complex things like item, potion or biome that are in a same file

This PR also:
- Adds data files generated by Minecraft from 1.13 to 1.16.3
- Use the Parser created previously to parse these minecraft json data files
- Effect
- Enchantment
- Entity
- Particle
- Block (Important point !!!!)
- Biome

### CODE REVIEW

**Comment by Geolykt** [comment]
I'd mark it as draft

**Comment by 0ddlyoko** [comment]
PR done, I'm ok for a review 😄

**Comment by 0ddlyoko** [comment]
Ready for a review :)

**Review by Geolykt — APPROVED** [review]
Python files look okay, json files and behaviour untested

**Comment by 0ddlyoko** [comment]
So is this PR ok ? May we merge it ?

**Comment by Geolykt** [comment]
The problem is that it's hard to test in it's entirety

**Comment by 0ddlyoko** [comment]
I'll edit the code to use minecraft data that is [here](https://github.com/PrismarineJS/minecraft-data/tree/master/data/pc)

**Comment by 0ddlyoko** [comment]
Close, I'll reopen it

**Pull request closed without merging**
